# Generated by Django 4.1.13 on 2025-09-14 09:39

import datetime
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('joining_date', models.DateField(default=datetime.date.today)),
                ('fee', models.FloatField()),
                ('tiffin_status', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'db_table': 'customer_collection',
                'managed': False,
            },
        ),
    ]
