# Generated by Django 5.2.8 on 2025-12-01 17:24

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joining_date', models.DateField(default=datetime.date.today)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_month', models.CharField(default='0000-00', max_length=7)),
                ('lunches_this_month', models.IntegerField(default=0)),
                ('dinners_this_month', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('L', 'Lunch'), ('D', 'Dinner')], max_length=1)),
                ('is_taken', models.BooleanField(default=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.customer')),
            ],
            options={
                'ordering': ['-date', 'meal_type'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user', 'name'], name='api_custome_user_id_e183ad_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['joining_date'], name='api_custome_joining_1f9227_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymeal',
            index=models.Index(fields=['customer', 'date'], name='api_dailyme_custome_959a85_idx'),
        ),
        migrations.AddIndex(
            model_name='dailymeal',
            index=models.Index(fields=['date'], name='api_dailyme_date_9c3f1a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailymeal',
            unique_together={('customer', 'date', 'meal_type')},
        ),
    ]
