# Generated by Django 5.2.6 on 2025-09-07 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiffinstatus',
            name='dinner',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tiffinstatus',
            name='lunch',
            field=models.BooleanField(default=True),
        ),
    ]
